import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  variable: "--font-spartan",
});

export const metadata: Metadata = {
  title: "Invoice App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${leagueSpartan.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-spartan lg:flex-row">
        <Sidebar />
        <main className="flex-1 px-6 pb-8 pt-[104px] lg:ml-[103px] lg:px-0 lg:pt-20">
          <div className="mx-auto max-w-[730px]">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
